Fixup for spec/libraries/roles_spec.rb
When running just this test in isolation, `geo_secondary_role` fails to
load as not enough stubbing has happened to allow the memory total to be
derived so you get:

  1) GitLabRoles roles config array supports providing a single role as a string
     Failure/Error: Gitlab.load_roles

     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./files/gitlab-cookbooks/package/libraries/config/roles/geo_secondary.rb:32:in `load_role'
     # ./files/gitlab-cookbooks/package/libraries/helpers/settings_helper.rb:149:in `block in load_roles'
     # ./files/gitlab-cookbooks/package/libraries/helpers/settings_helper.rb:147:in `each'
     # ./files/gitlab-cookbooks/package/libraries/helpers/settings_helper.rb:147:in `load_roles'
     # ./spec/libraries/roles_spec.rb:27:in `block (3 levels) in <top (required)>'

Here we just paper over this by choosing *another* role to test for in
the 'single role as a string' example.