Attempt to retry twice to determine Redis server version
We had two different customers upgrade GitLab and run into `stderr:
Error: Connection reset by peer` when attempting to determine the
Redis version. This appears to have occurred because `gitlab-ctl
reconfigure` can restart Redis right before it checks the version.
This causes the `gitlab-ctl reconfigure` to fail outright.

To avoid this failure mode, set the Chef `retries` parameter to 2. By
default the `retry_delay` is 2 seconds.

Relates to
https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/8597

Changelog: fixed