Require 'rainbow' so we can use it
The rainbow gem hadn't been loaded before it'd been used, which means
when renew-le-certs fails, we get an error about being unable to call
`Rainbow()`

    /opt/gitlab/embedded/service/omnibus-ctl/letsencrypt.rb:22:in `block in load_file': undefined method `Rainbow' for #<Omnibus::Ctl:0x00000000023c1908> (NoMethodError)
            from /opt/gitlab/embedded/lib/ruby/gems/2.3.0/gems/omnibus-ctl-0.5.0/lib/omnibus-ctl.rb:202:in `block in add_command_under_category'
            from /opt/gitlab/embedded/lib/ruby/gems/2.3.0/gems/omnibus-ctl-0.5.0/lib/omnibus-ctl.rb:730:in `run'
            from /opt/gitlab/embedded/lib/ruby/gems/2.3.0/gems/omnibus-ctl-0.5.0/bin/omnibus-ctl:31:in `<top (required)>'
            from /opt/gitlab/embedded/bin/omnibus-ctl:23:in `load'
            from /opt/gitlab/embedded/bin/omnibus-ctl:23:in `<main>'