Avoid generic NoMethodError on non-Patroni nodes
"gitlab-ctl patroni" commands printed out the raw error:
undefined method `[]' for nil:NilClass

Introducing the helper methods Patroni.patroni_attributes and
Utils.no_config_error! should provide a better user experience.

Changelog: changed